name: Python linting

on: 
  - workflow_dispatch

jobs: 
  lintingOperation:   # this is the name of a job
    permissions:
      security-events: read
    runs-on: ubuntu-latest   # this is the snowglobe to use for the work
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13' 
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "main.py"  # Directory to check
